import { randomUUID } from "node:crypto";

export const roles = {
  ADMIN: "Admin",
  CELL_HEAD: "Cell Head",
  CELL_MEMBER: "Cell Member",
};

export const cells = [
  { id: "cell-obc", name: "OBC Cell" },
  { id: "cell-population-studies", name: "Population Studies Cell" },
  { id: "cell-sc", name: "SC Cell" },
  { id: "cell-women", name: "Women Cell" },
  { id: "cell-womens-study", name: "Women's Study Cell" },
  { id: "cell-international", name: "International Students Cell" },
  { id: "cell-minority", name: "Minority Cell" },
  { id: "cell-counselling", name: "Counselling & Mentoring Cell" },
  { id: "cell-differently-abled", name: "Differently Abled Cell" },
  { id: "cell-remedial", name: "Remedial Coaching Cell" },
  { id: "cell-nss", name: "National Service Scheme (NSS) Cell" },
  { id: "cell-posh", name: "Prevention of Sexual Harassment (POSH) Cell" },
  { id: "cell-gender", name: "Gender Sensitization Cell" },
  { id: "cell-human-studies", name: "Human Studies Cell" },
];

export const users = [
  {
    id: "user-admin",
    name: "Chairman Admin",
    email: "abdul000muqeet@gmail.com",
    password: "admin123",
    role: roles.ADMIN,
    cellId: null,
    phone: "N/A",
    designation: "Chairman",
  },
  {
    id: "user-head-obc-salim-sharieff",
    name: "Dr. Salim Sharieff",
    email: "salims.me@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-obc",
    phone: "9620525177",
    designation: "Cell Head",
  },
  {
    id: "user-member-obc-dinesh-h-a",
    name: "Prof. Dinesh H A",
    email: "dineshh.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-obc",
    phone: "9620007996",
    designation: "Cell Member",
  },
  {
    id: "user-member-obc-najmusher-h",
    name: "Prof. Najmusher H",
    email: "najmusherh.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-obc",
    phone: "9845924416",
    designation: "Cell Member",
  },
  {
    id: "user-member-obc-mohammad-aamir-almas",
    name: "Prof. Mohammad Aamir Almas",
    email: "aamirm.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-obc",
    phone: "9739063960",
    designation: "Cell Member",
  },
  {
    id: "user-member-obc-suhas-a-r",
    name: "Dr. Suhas A R",
    email: "suhasa.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-obc",
    phone: "7259551230",
    designation: "Cell Member",
  },
  {
    id: "user-member-obc-sangappa-gani",
    name: "Dr. Sangappa Gani",
    email: "sangappa.hu@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-obc",
    phone: "9743171324",
    designation: "Cell Member",
  },
  {
    id: "user-member-obc-umme-salma",
    name: "Prof. Umme Salma",
    email: "ummesalma.mt@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-obc",
    phone: "9964384378",
    designation: "Cell Member",
  },
  {
    id: "user-member-obc-bharath-v",
    name: "Prof. Bharath V",
    email: "bharath.aiml@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-obc",
    phone: "7338405853",
    designation: "Cell Member",
  },
  {
    id: "user-member-obc-ayesha-anjum",
    name: "Prof. Ayesha Anjum",
    email: "ayesha.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-obc",
    phone: "9591478897",
    designation: "Cell Member",
  },
  {
    id: "user-member-obc-sneha-k",
    name: "Prof. Sneha K",
    email: "snehak.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-obc",
    phone: "7306945259",
    designation: "Cell Member",
  },
  {
    id: "user-member-obc-rousheen-taj",
    name: "Prof. Rousheen Taj",
    email: "rousheentaj.dg@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-obc",
    phone: "8660962073",
    designation: "Cell Member",
  },
  {
    id: "user-member-obc-rizwan-pasha",
    name: "Prof. Rizwan Pasha",
    email: "prizwan917@gmail.com",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-obc",
    phone: "8867734830",
    designation: "Cell Member",
  },
  {
    id: "user-head-sc-seema-shivapur",
    name: "Prof. Seema Shivapur",
    email: "shivapur.cs@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-sc",
    phone: "8861620506",
    designation: "Cell Head",
  },
  {
    id: "user-member-sc-balaji-vijayan-v",
    name: "Dr. Balaji Vijayan V",
    email: "balaji.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-sc",
    phone: "9943397400",
    designation: "Cell Member",
  },
  {
    id: "user-member-sc-lakshmi-devi-d",
    name: "Prof. Lakshmi Devi D",
    email: "lakshmidevi.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-sc",
    phone: "7022515680",
    designation: "Cell Member",
  },
  {
    id: "user-member-sc-lokesh-m-r",
    name: "Dr. Lokesh M R",
    email: "lokesh.ch@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-sc",
    phone: "9035469862",
    designation: "Cell Member",
  },
  {
    id: "user-member-sc-manjuladevi-m",
    name: "Dr. Manjuladevi M",
    email: "manjuladevi.kan@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-sc",
    phone: "8310311613",
    designation: "Cell Member",
  },
  {
    id: "user-member-sc-s-sivasundarapandian",
    name: "Dr. S. Sivasundarapandian",
    email: "sivasundara.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-sc",
    phone: "9382712928",
    designation: "Cell Member",
  },
  {
    id: "user-member-sc-manu-prasad-m-p",
    name: "Prof. Manu Prasad M P",
    email: "manup.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-sc",
    phone: "8660844634",
    designation: "Cell Member",
  },
  {
    id: "user-member-sc-naresh-m-k",
    name: "Prof. Naresh M K",
    email: "nareshm.mt@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-sc",
    phone: "7892667968",
    designation: "Cell Member",
  },
  {
    id: "user-member-sc-piruthiviraj-p",
    name: "Dr. Piruthiviraj P",
    email: "piruthiviraj.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-sc",
    phone: "9741884914",
    designation: "Cell Member",
  },
  {
    id: "user-member-sc-panthagani-srilakshmi",
    name: "Prof. Panthagani Srilakshmi",
    email: "srilakshmip.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-sc",
    phone: "6363534951",
    designation: "Cell Member",
  },
  {
    id: "user-member-sc-naveen",
    name: "Prof. Naveen",
    email: "naveen.dg@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-sc",
    phone: "8105107077",
    designation: "Cell Member",
  },
  {
    id: "user-head-women-tabassum-ara",
    name: "Dr. Tabassum Ara",
    email: "hod.aiml@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-women",
    phone: "8553754383",
    designation: "Cell Head",
  },
  {
    id: "user-member-women-khallikkunaisa",
    name: "Prof. Khallikkunaisa",
    email: "khallikkunaisa.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "9880137269",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-suraiya-tarannum",
    name: "Dr. Suraiya Tarannum",
    email: "suraiyat.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "9901929992",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-nadeem-pasha-k",
    name: "Prof. Nadeem Pasha K",
    email: "nadeemp.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "9844103602",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-vinay-a-l",
    name: "Mr. Vinay A L",
    email: "hod_sss@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "9731761019",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-nusrat-ul-reshma",
    name: "Mrs. Nusrat-ul-Reshma",
    email: "nusrathu.ac@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "7795802667",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-purohit-mansi-rajendrakumar",
    name: "Ms. Purohit Mansi Rajendrakumar",
    email: "1hk21is087@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "7899391595",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-nandinee-das",
    name: "Ms. Nandinee Das",
    email: "1hk21cs108@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "8474027360",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-farmaan-fahim-ahmed-khan",
    name: "Mr. Farmaan Fahim Ahmed Khan",
    email: "1hk21ec130@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "9019366329",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-badrunnisa",
    name: "Mrs. Badrunnisa",
    email: "budrunnisaadvocate@gmail.com",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "9845037957",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-suja-warriar",
    name: "Mrs. Suja Warriar",
    email: "sujawarriar@wequity.tech",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "7259001155",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-r-k-mulla",
    name: "Mr. R K Mulla",
    email: "mullarajesab@gmail.com",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "9945042171",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-noor-jahan",
    name: "Dr. Noor Jahan",
    email: "noorjahan.dg@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "9035445078",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-bhavya",
    name: "Prof. Bhavya",
    email: "bhavya.puc@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "8660710796",
    designation: "Cell Member",
  },
  {
    id: "user-member-women-rachel-sarah",
    name: "Prof. Rachel Sarah",
    email: "rachel@onesb.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-women",
    phone: "8660500899",
    designation: "Cell Member",
  },
  {
    id: "user-head-womens-study-tabassum-ara",
    name: "Dr. Tabassum Ara",
    email: "hod.aiml@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-womens-study",
    phone: "8553754383",
    designation: "Cell Head",
  },
  {
    id: "user-member-womens-study-khallikkunaisa",
    name: "Prof. Khallikkunaisa",
    email: "khallikkunaisa.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-womens-study",
    phone: "9880137269",
    designation: "Cell Member",
  },
  {
    id: "user-member-womens-study-sumaiya-banu",
    name: "Prof. Sumaiya Banu",
    email: "sumaiyab.mb@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-womens-study",
    phone: "9844048699",
    designation: "Cell Member",
  },
  {
    id: "user-member-womens-study-sharada-k-a",
    name: "Dr. Sharada K A",
    email: "sharada.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-womens-study",
    phone: "9986834922",
    designation: "Cell Member",
  },
  {
    id: "user-member-womens-study-zahira-tabassum",
    name: "Dr. Zahira Tabassum",
    email: "zahirat.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-womens-study",
    phone: "9916701624",
    designation: "Cell Member",
  },
  {
    id: "user-member-womens-study-suraiya-tarannum",
    name: "Dr. Suraiya Tarannum",
    email: "suraiyat.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-womens-study",
    phone: "9901929992",
    designation: "Cell Member",
  },
  {
    id: "user-member-womens-study-mohsina-taj",
    name: "Dr. Mohsina Taj",
    email: "mohsina.ph@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-womens-study",
    phone: "9916501423",
    designation: "Cell Member",
  },
  {
    id: "user-member-womens-study-umme-salma",
    name: "Prof. Umme Salma",
    email: "ummesalma.mt@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-womens-study",
    phone: "9964384378",
    designation: "Cell Member",
  },
  {
    id: "user-member-womens-study-sujitha",
    name: "Dr. Sujitha",
    email: "sujitha.hu@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-womens-study",
    phone: "9703530543",
    designation: "Cell Member",
  },
  {
    id: "user-member-womens-study-bharath-v",
    name: "Prof. Bharath V",
    email: "bharath.aiml@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-womens-study",
    phone: "7338405853",
    designation: "Cell Member",
  },
  {
    id: "user-member-womens-study-sneha-k",
    name: "Prof. Sneha K",
    email: "snehak.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-womens-study",
    phone: "7306945259",
    designation: "Cell Member",
  },
  {
    id: "user-member-womens-study-manjuladevi-m",
    name: "Dr. Manjuladevi M",
    email: "manjuladevi.kan@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-womens-study",
    phone: "8310311613",
    designation: "Cell Member",
  },
  {
    id: "user-member-womens-study-noor-jahan",
    name: "Dr. Noor Jahan",
    email: "noorjahan.dg@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-womens-study",
    phone: "9035445078",
    designation: "Cell Member",
  },
  {
    id: "user-head-differently-abled-a-syed-mustafa",
    name: "Dr. A Syed Mustafa",
    email: "mustafas.is@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-differently-abled",
    phone: "9844011062",
    designation: "Cell Head",
  },
  {
    id: "user-member-differently-abled-naresh-m-k",
    name: "Prof. Naresh M K",
    email: "nareshm.mt@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "7892667968",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-kavitha-d",
    name: "Prof. Kavitha D",
    email: "kavithad.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "9620600020",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-venkatesan-c",
    name: "Dr. Venkatesan C",
    email: "venkatesanc.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "9626465862",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-esther-priscilla-e",
    name: "Prof. Esther Priscilla E",
    email: "priscillae.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "8197024664",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-bharath-v",
    name: "Prof. Bharath V",
    email: "bharath.aiml@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "7338405853",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-abdul-azeez",
    name: "Dr. Abdul Azeez",
    email: "abdulazeez.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "9900443481",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-rashmi-rani-samantaray",
    name: "Prof. Rashmi Rani Samantaray",
    email: "rashmirs.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "9880629707",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-girijalakshmi",
    name: "Prof. Girijalakshmi",
    email: "girijal.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "9611327376",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-nawaz-ahmed",
    name: "Prof. Nawaz Ahmed",
    email: "nawaza.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "9036745305",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-shubha-a",
    name: "Prof. Shubha A",
    email: "anands.ch@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "9591469148",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-karuna-kumari",
    name: "Dr. Karuna Kumari",
    email: "karuna.phy@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "8235038261",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-samiya-ibrahim",
    name: "Ms. Samiya Ibrahim",
    email: "1hk23is64@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "9986721224",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-mahesh",
    name: "Mr. Mahesh",
    email: "mahesha.dg@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "7349695721",
    designation: "Cell Member",
  },
  {
    id: "user-member-differently-abled-rizwan-pasha",
    name: "Prof. Rizwan Pasha",
    email: "prizwan917@gmail.com",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-differently-abled",
    phone: "8867734830",
    designation: "Cell Member",
  },
  {
    id: "user-head-population-studies-khallikkunaisa",
    name: "Prof. Khallikkunaisa",
    email: "khallikkunaisa.cs@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-population-studies",
    phone: "9880137269",
    designation: "Cell Head",
  },
  {
    id: "user-member-population-studies-sumaiya-banu",
    name: "Prof. Sumaiya Banu",
    email: "sumaiyab.mb@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-population-studies",
    phone: "9844048699",
    designation: "Cell Member",
  },
  {
    id: "user-member-population-studies-dushyantha-n-d",
    name: "Dr. Dushyantha N D",
    email: "dushyantha.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-population-studies",
    phone: "7337712423",
    designation: "Cell Member",
  },
  {
    id: "user-member-population-studies-lijimol-k",
    name: "Prof. Lijimol K",
    email: "lijimolk.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-population-studies",
    phone: "8277250483",
    designation: "Cell Member",
  },
  {
    id: "user-member-population-studies-aswathy-j-s",
    name: "Prof. Aswathy J S",
    email: "aswathyj.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-population-studies",
    phone: "8129665012",
    designation: "Cell Member",
  },
  {
    id: "user-member-population-studies-induja-p",
    name: "Prof. Induja P",
    email: "induja.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-population-studies",
    phone: "9698849170",
    designation: "Cell Member",
  },
  {
    id: "user-member-population-studies-younus-pasha",
    name: "Dr. Younus Pasha",
    email: "younusp.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-population-studies",
    phone: "8722715742",
    designation: "Cell Member",
  },
  {
    id: "user-member-population-studies-ishrath",
    name: "Prof. Ishrath",
    email: "ishrath.mt@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-population-studies",
    phone: "9902233067",
    designation: "Cell Member",
  },
  {
    id: "user-member-population-studies-samahira-begum",
    name: "Prof. Samahira Begum",
    email: "samahirab.hu@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-population-studies",
    phone: "9686197860",
    designation: "Cell Member",
  },
  {
    id: "user-member-population-studies-jayasimha-h-n",
    name: "Prof. Jayasimha H N",
    email: "jayasimhna@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-population-studies",
    phone: "9740570762",
    designation: "Cell Member",
  },
  {
    id: "user-member-population-studies-hashinur-islam",
    name: "Dr. Hashinur Islam",
    email: "hashinur.aiml@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-population-studies",
    phone: "8972140206",
    designation: "Cell Member",
  },
  {
    id: "user-member-population-studies-kokila-n",
    name: "Prof. Kokila N",
    email: "kokilan.dg@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-population-studies",
    phone: "9164821303",
    designation: "Cell Member",
  },
  {
    id: "user-head-international-sumaiya-banu",
    name: "Prof. Sumaiya Banu",
    email: "sumaiyab.mb@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-international",
    phone: "9844048699",
    designation: "Cell Head",
  },
  {
    id: "user-member-international-sujitha",
    name: "Dr. Sujitha",
    email: "sujitha.hu@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-international",
    phone: "9703530543",
    designation: "Cell Member",
  },
  {
    id: "user-member-international-gowri-n-r",
    name: "Prof. Gowri N R",
    email: "gowrin.hu@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-international",
    phone: "9487453142",
    designation: "Cell Member",
  },
  {
    id: "user-member-international-tansif-khan",
    name: "Prof. Tansif Khan",
    email: "tansifkhan.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-international",
    phone: "9880038408",
    designation: "Cell Member",
  },
  {
    id: "user-member-international-noor-ayesha",
    name: "Prof. Noor Ayesha",
    email: "noorayesha.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-international",
    phone: "9035724857",
    designation: "Cell Member",
  },
  {
    id: "user-member-international-muskan-s",
    name: "Prof. Muskan S",
    email: "muskans.aiml@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-international",
    phone: "9490428270",
    designation: "Cell Member",
  },
  {
    id: "user-member-international-nandini-k",
    name: "Prof. Nandini K",
    email: "nandinik.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-international",
    phone: "9845327648",
    designation: "Cell Member",
  },
  {
    id: "user-member-international-sarumathi",
    name: "Prof. Sarumathi",
    email: "sarumathi.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-international",
    phone: "9942404778",
    designation: "Cell Member",
  },
  {
    id: "user-member-international-divananda",
    name: "Mr. Divananda",
    email: "divanandag@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-international",
    phone: "9986866406",
    designation: "Cell Member",
  },
  {
    id: "user-member-international-awad-zuhair",
    name: "Mr. Awad Zuhair",
    email: "1hk22ec019@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-international",
    phone: "6361651512",
    designation: "Cell Member",
  },
  {
    id: "user-member-international-krishna-rawal",
    name: "Mr. Krishna Rawal",
    email: "1hk24cs113@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-international",
    phone: "9113009026",
    designation: "Cell Member",
  },
  {
    id: "user-member-international-manish-kumar-jha",
    name: "Mr. Manish Kumar Jha",
    email: "1hk24cs126@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-international",
    phone: "9234571860",
    designation: "Cell Member",
  },
  {
    id: "user-member-international-pallavi",
    name: "Dr. Pallavi",
    email: "pallavi.dg@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-international",
    phone: "9483041973",
    designation: "Cell Member",
  },
  {
    id: "user-head-minority-maaz-ahmed",
    name: "Dr. Maaz Ahmed",
    email: "ahmedmz.ec@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-minority",
    phone: "9035452495",
    designation: "Cell Head",
  },
  {
    id: "user-member-minority-yousuf-madar",
    name: "Prof. Yousuf Madar",
    email: "yousufmadar.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-minority",
    phone: "9972214722",
    designation: "Cell Member",
  },
  {
    id: "user-member-minority-tahir-naquash-h-b",
    name: "Prof. Tahir Naquash H B",
    email: "tahir.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-minority",
    phone: "9036937955",
    designation: "Cell Member",
  },
  {
    id: "user-member-minority-husna-tabassum",
    name: "Prof. Husna Tabassum",
    email: "husnatabassum.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-minority",
    phone: "9945332367",
    designation: "Cell Member",
  },
  {
    id: "user-member-minority-naheem-m-r",
    name: "Prof. Naheem M R",
    email: "naheem.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-minority",
    phone: "9591797221",
    designation: "Cell Member",
  },
  {
    id: "user-member-minority-shahista-tabassum",
    name: "Prof. Shahista Tabassum",
    email: "shahista.aiml@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-minority",
    phone: "8951568944",
    designation: "Cell Member",
  },
  {
    id: "user-member-minority-sheikh-haroon-safdar",
    name: "Prof. Sheikh Haroon Safdar",
    email: "haroons.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-minority",
    phone: "9480429927",
    designation: "Cell Member",
  },
  {
    id: "user-member-minority-abdul-mujeeb-n",
    name: "Prof. Abdul Mujeeb N",
    email: "mujeeba.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-minority",
    phone: "9632908465",
    designation: "Cell Member",
  },
  {
    id: "user-member-minority-mohsina-taj",
    name: "Dr. Mohsina Taj",
    email: "mohsina.ph@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-minority",
    phone: "9916501423",
    designation: "Cell Member",
  },
  {
    id: "user-member-minority-sufia-banu",
    name: "Dr. Sufia Banu",
    email: "sufiabanu.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-minority",
    phone: "9844567828",
    designation: "Cell Member",
  },
  {
    id: "user-member-minority-mohammed-khizerulla",
    name: "Dr. Mohammed Khizerulla",
    email: "mohammedkhizerulla@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-minority",
    phone: "9845267977",
    designation: "Cell Member",
  },
  {
    id: "user-member-minority-rizwan-pasha",
    name: "Prof. Rizwan Pasha",
    email: "prizwan917@gmail.com",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-minority",
    phone: "8867734830",
    designation: "Cell Member",
  },
  {
    id: "user-head-remedial-chandrakumar-k",
    name: "Dr. Chandrakumar K",
    email: "chandrakumar.ph@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-remedial",
    phone: "9916041209",
    designation: "Cell Head",
  },
  {
    id: "user-member-remedial-c-s-nagabhushana",
    name: "Dr. C S Nagabhushana",
    email: "nagabhushana.hod@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9964189984",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-umme-salma",
    name: "Prof. Umme Salma",
    email: "ummesalma.mt@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9964384378",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-lakshmi-k",
    name: "Prof. Lakshmi K",
    email: "lakshmik.ph@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9980515236",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-minal-khandre",
    name: "Prof. Minal Khandre",
    email: "minalk.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "7710050765",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-v-sivakumar",
    name: "Dr. V Sivakumar",
    email: "sivakumar.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9844086459",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-piruthiviraj-p",
    name: "Dr. Piruthiviraj P",
    email: "piruthiviraj.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9741884914",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-shruthi-v-kulkarni",
    name: "Prof. Shruthi V Kulkarni",
    email: "shruthik.aiml@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9916573889",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-sathya-bama-s",
    name: "Prof. Sathya Bama S",
    email: "ssbama.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9686913642",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-ramachandra-kulkarni",
    name: "Prof. Ramachandra Kulkarni",
    email: "ramachandra.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9620429572",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-pushparekha",
    name: "Prof. Pushparekha",
    email: "pushparekha.ch@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9482488071",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-sharmada-u",
    name: "Prof. Sharmada U",
    email: "sharmadau.mt@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "8050299241",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-karuna-kumari",
    name: "Dr. Karuna Kumari",
    email: "karuna.phy@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "8235038261",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-jayasimha",
    name: "Prof. Jayasimha",
    email: "jayasimhna@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9740570762",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-dhanush",
    name: "Prof. Dhanush",
    email: "dhanush.hu@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9380683029",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-lavanya",
    name: "Prof. Lavanya",
    email: "lavanya.bba@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9945495963",
    designation: "Cell Member",
  },
  {
    id: "user-member-remedial-santosh-kumar",
    name: "Prof. Santosh Kumar",
    email: "santoshgm.puc@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-remedial",
    phone: "9901198473",
    designation: "Cell Member",
  },
  {
    id: "user-head-nss-salim-sharieff",
    name: "Dr. Salim Sharieff",
    email: "salims.me@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-nss",
    phone: "9844048699",
    designation: "Cell Head",
  },
  {
    id: "user-member-nss-sumaiya-banu",
    name: "Prof. Sumaiya Banu",
    email: "sumaiyab.mb@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "9620525177",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-s-arshad-pasha",
    name: "Dr. S Arshad Pasha",
    email: "arshadp.ph@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "9844066701",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-naheem-m-r",
    name: "Prof. Naheem M R",
    email: "naheem.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "9591797221",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-shantarani-s-birajdar",
    name: "Prof. Shantarani S Birajdar",
    email: "shantarani.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "9731628364",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-bharath-v",
    name: "Prof. Bharath V",
    email: "bharath.aiml@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "7338405853",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-samparna-rautray",
    name: "Prof. Samparna Rautray",
    email: "samparna.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "9741428547",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-abdul-azeez",
    name: "Dr. Abdul Azeez",
    email: "abdulazeez.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "9900443481",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-tansif-khan",
    name: "Prof. Tansif Khan",
    email: "tansifkhan.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "9880038408",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-rashmi-c",
    name: "Prof. Rashmi C",
    email: "rashmi.cv@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "7349082226",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-shrisha-k",
    name: "Prof. Shrisha K",
    email: "shrisha.hu@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "8892137661",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-chetanan-n",
    name: "Prof. Chetanan N",
    email: "chetanan.phy@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "9986965294",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-lokesh-m-r",
    name: "Dr. Lokesh M R",
    email: "lokesh.ch@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "9035469862",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-maha-chethan",
    name: "Mr. Maha Chethan",
    email: "mahachethan.sports@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "9686525051",
    designation: "Cell Member",
  },
  {
    id: "user-member-nss-kavya",
    name: "Prof. Kavya",
    email: "kavya@onesb.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-nss",
    phone: "8197543935",
    designation: "Cell Member",
  },
  {
    id: "user-head-posh-khallikkunaisa",
    name: "Prof. Khallikkunaisa",
    email: "khallikkunaisa.cs@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-posh",
    phone: "9880137269",
    designation: "Cell Head",
  },
  {
    id: "user-member-posh-suraiya-tarannum",
    name: "Dr. Suraiya Tarannum",
    email: "suraiyat.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-posh",
    phone: "9901929992",
    designation: "Cell Member",
  },
  {
    id: "user-member-posh-nadeem-pasha-k",
    name: "Prof. Nadeem Pasha K",
    email: "nadeemp.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-posh",
    phone: "9844103602",
    designation: "Cell Member",
  },
  {
    id: "user-member-posh-vinay-a-l",
    name: "Mr. Vinay A L",
    email: "hod_sss@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-posh",
    phone: "9731761019",
    designation: "Cell Member",
  },
  {
    id: "user-member-posh-nusrat-ul-reshma",
    name: "Mrs. Nusrat-ul-Reshma",
    email: "nusrathu.ac@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-posh",
    phone: "7795802667",
    designation: "Cell Member",
  },
  {
    id: "user-member-posh-purohit-mansi",
    name: "Ms. Purohit Mansi",
    email: "1hk21is087@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-posh",
    phone: "7899391595",
    designation: "Cell Member",
  },
  {
    id: "user-member-posh-nandinee-das",
    name: "Ms. Nandinee Das",
    email: "1hk21cs108@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-posh",
    phone: "8474027360",
    designation: "Cell Member",
  },
  {
    id: "user-member-posh-farmaan-fahim-ahmed",
    name: "Mr. Farmaan Fahim Ahmed",
    email: "1hk21ec130@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-posh",
    phone: "9019366329",
    designation: "Cell Member",
  },
  {
    id: "user-member-posh-badrunnisa",
    name: "Mrs. Badrunnisa",
    email: "budrunnisaadvocate@gmail.com",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-posh",
    phone: "9845037957",
    designation: "Cell Member",
  },
  {
    id: "user-member-posh-smitha-shankar",
    name: "Prof. Smitha Shankar",
    email: "smithas.dg@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-posh",
    phone: "8867343688",
    designation: "Cell Member",
  },
  {
    id: "user-member-posh-bhavya",
    name: "Prof. Bhavya",
    email: "bhavya.puc@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-posh",
    phone: "8660710796",
    designation: "Cell Member",
  },
  {
    id: "user-member-posh-jitin",
    name: "Prof. Jitin",
    email: "jitin@onesb.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-posh",
    phone: "7306907271",
    designation: "Cell Member",
  },
  {
    id: "user-head-gender-khallikkunaisa",
    name: "Prof. Khallikkunaisa",
    email: "khallikkunaisa.cs@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-gender",
    phone: "9880137269",
    designation: "Cell Head",
  },
  {
    id: "user-member-gender-suraiya-tarannum",
    name: "Dr. Suraiya Tarannum",
    email: "suraiyat.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-gender",
    phone: "9901929992",
    designation: "Cell Member",
  },
  {
    id: "user-member-gender-nadeem-pasha-k",
    name: "Prof. Nadeem Pasha K",
    email: "nadeemp.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-gender",
    phone: "9844103602",
    designation: "Cell Member",
  },
  {
    id: "user-member-gender-vinay-a-l",
    name: "Mr. Vinay A L",
    email: "hod_sss@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-gender",
    phone: "9731761019",
    designation: "Cell Member",
  },
  {
    id: "user-member-gender-nusrat-ul-reshma",
    name: "Mrs. Nusrat-ul-Reshma",
    email: "nusrathu.ac@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-gender",
    phone: "7795802667",
    designation: "Cell Member",
  },
  {
    id: "user-member-gender-purohit-mansi",
    name: "Ms. Purohit Mansi",
    email: "1hk21is087@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-gender",
    phone: "7899391595",
    designation: "Cell Member",
  },
  {
    id: "user-member-gender-nandinee-das",
    name: "Ms. Nandinee Das",
    email: "1hk21cs108@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-gender",
    phone: "8474027360",
    designation: "Cell Member",
  },
  {
    id: "user-member-gender-farmaan-fahim-ahmed",
    name: "Mr. Farmaan Fahim Ahmed",
    email: "1hk21ec130@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-gender",
    phone: "9019366329",
    designation: "Cell Member",
  },
  {
    id: "user-member-gender-badrunnisa",
    name: "Mrs. Badrunnisa",
    email: "budrunnisaadvocate@gmail.com",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-gender",
    phone: "9845037957",
    designation: "Cell Member",
  },
  {
    id: "user-member-gender-kavya-j",
    name: "Prof. Kavya J",
    email: "kavya.dg@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-gender",
    phone: "9976158758",
    designation: "Cell Member",
  },
  {
    id: "user-member-gender-bhavya",
    name: "Prof. Bhavya",
    email: "bhavya.puc@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-gender",
    phone: "8660710796",
    designation: "Cell Member",
  },
  {
    id: "user-head-human-studies-khallikkunaisa",
    name: "Prof. Khallikkunaisa",
    email: "khallikkunaisa.cs@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-human-studies",
    phone: "9880137269",
    designation: "Cell Head",
  },
  {
    id: "user-member-human-studies-sumaiya-banu",
    name: "Prof. Sumaiya Banu",
    email: "sumaiyab.mb@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-human-studies",
    phone: "9844048699",
    designation: "Cell Member",
  },
  {
    id: "user-member-human-studies-anees-fatima",
    name: "Prof. Anees Fatima",
    email: "aneesfathima.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-human-studies",
    phone: "8861024869",
    designation: "Cell Member",
  },
  {
    id: "user-member-human-studies-umme-salma",
    name: "Prof. Umme Salma",
    email: "ummesalma.mt@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-human-studies",
    phone: "9964384378",
    designation: "Cell Member",
  },
  {
    id: "user-member-human-studies-bharath-v",
    name: "Prof. Bharath V",
    email: "bharath.aiml@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-human-studies",
    phone: "7338405853",
    designation: "Cell Member",
  },
  {
    id: "user-member-human-studies-gowri-n-r",
    name: "Prof. Gowri N R",
    email: "gowrin.hu@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-human-studies",
    phone: "9487453142",
    designation: "Cell Member",
  },
  {
    id: "user-member-human-studies-shubha-a",
    name: "Prof. Shubha A",
    email: "anands.ch@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-human-studies",
    phone: "9591469148",
    designation: "Cell Member",
  },
  {
    id: "user-member-human-studies-ramachandra-kulkarni",
    name: "Prof. Ramachandra Kulkarni",
    email: "ramachandra.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-human-studies",
    phone: "9620429572",
    designation: "Cell Member",
  },
  {
    id: "user-member-human-studies-sufiya-banu",
    name: "Dr. Sufiya Banu",
    email: "sufiabanu.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-human-studies",
    phone: "9844567828",
    designation: "Cell Member",
  },
  {
    id: "user-member-human-studies-sharada-k-a",
    name: "Dr. Sharada K A",
    email: "sharada.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-human-studies",
    phone: "9986834922",
    designation: "Cell Member",
  },
  {
    id: "user-member-human-studies-sneha-k",
    name: "Prof. Sneha K",
    email: "snehak.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-human-studies",
    phone: "7306945259",
    designation: "Cell Member",
  },
  {
    id: "user-member-human-studies-esther-priscilla-e",
    name: "Prof. Esther Priscilla E",
    email: "priscillae.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-human-studies",
    phone: "8197024664",
    designation: "Cell Member",
  },
  {
    id: "user-member-human-studies-nisha-johnson",
    name: "Prof. Nisha Johnson",
    email: "nishaj.dg@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-human-studies",
    phone: "8904195596",
    designation: "Cell Member",
  },
  {
    id: "user-head-counselling-smitha-kurian",
    name: "Dr. Smitha Kurian",
    email: "hod.cse@hkbk.edu.in",
    password: "head123",
    role: roles.CELL_HEAD,
    cellId: "cell-counselling",
    phone: "9980492375",
    designation: "Cell Head",
  },
  {
    id: "user-member-counselling-sheikh-haroon-safdar",
    name: "Prof. Sheikh Haroon Safdar",
    email: "haroons.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "9480429927",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-vinay-a-l",
    name: "Mr. Vinay A L",
    email: "hod_sss@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "9731761019",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-salim-sharieff",
    name: "Dr. Salim Sharieff",
    email: "salims.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "9620525177",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-sumaiya-banu",
    name: "Prof. Sumaiya Banu",
    email: "sumaiyab.mb@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "9844048699",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-mary-stella-j",
    name: "Prof. Mary Stella J",
    email: "marys.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "9036898411",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-juliet-johny",
    name: "Prof. Juliet Johny",
    email: "julietjohny.cs@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "9526550873",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-shantarani-s-birajdar",
    name: "Prof. Shantarani S Birajdar",
    email: "shantarani.is@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "9731628364",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-bharath-v",
    name: "Prof. Bharath V",
    email: "bharath.aiml@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "7338405853",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-syeda-noor-fathima",
    name: "Prof. Syeda Noor Fathima",
    email: "snoorfathima.ec@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "8861396228",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-abdul-mujeeb-n",
    name: "Prof. Abdul Mujeeb N",
    email: "mujeeba.me@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "9632908465",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-p-raja",
    name: "Prof. P. Raja",
    email: "rajap.ph@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "9578211721",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-sharmada",
    name: "Prof. Sharmada",
    email: "sharmadau.mt@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "8050299241",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-jayasimha-h-n",
    name: "Prof. Jayasimha H N",
    email: "jayasimhna@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "9740570762",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-sirisha-k",
    name: "Prof. Sirisha K",
    email: "shrisha.hu@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "8892137661",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-subhan-shaik",
    name: "Prof. Subhan Shaik",
    email: "subhan.dg@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "9741212310",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-siddalingesh-akk",
    name: "Prof. Siddalingesh Akk",
    email: "siddalingesh.puc@hkbk.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "8792325056",
    designation: "Cell Member",
  },
  {
    id: "user-member-counselling-karthika",
    name: "Prof. Karthika",
    email: "karthika@onesb.edu.in",
    password: "member123",
    role: roles.CELL_MEMBER,
    cellId: "cell-counselling",
    phone: "9745015133",
    designation: "Cell Member",
  },
];

export const circulars = [];

export const meetings = [];

export const reports = [];

export const notifications = [];

export function createNotification({ userId, title, message, type, entityId }) {
  const notification = {
    id: randomUUID(),
    userId,
    title,
    message,
    type,
    entityId,
    read: false,
    createdAt: new Date().toISOString(),
  };
  notifications.unshift(notification);
  return notification;
}

export function findCellName(cellId) {
  return cells.find((cell) => cell.id === cellId)?.name ?? "All Cells";
}
